version: "3.3"
   
services:
    interface:
        build:
            context: ./interface
        entrypoint: ["sudo", "sh", "/app/entrypoint.sh"]
        volumes:
            - ./interface:/app
        ports:
            - "3000:3000"
        networks:
            - app-network
        depends_on:
            - api

    api:
        build: 
            context: ./api
            args:
                - DEV=true
        entrypoint: ["sh", "/app/entrypoint.sh"]
        volumes:
            - ./api:/app
        ports:
            - "8000:8000"
        environment:
            - DB_HOST=db
            - DB_NAME=devdb
            - DB_USER=devuser
            - DB_PASSWORD=changeme
            - DEBUG=1
        networks:
            - app-network
        depends_on:
            - db

    db:
        image: postgres:16-alpine
        volumes: 
            - dev-db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=devdb
            - POSTGRES_USER=devuser
            - POSTGRES_PASSWORD=changeme
        networks:
            - app-network

volumes:
    dev-db-data:

networks:
    app-network: